apiVersion: v1
kind: Service
metadata:
  name:  {{ template "nats-streaming-server.fullname" . }}
  labels:
    app:  {{ template "nats-streaming-server.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
spec:
  selector:
    app:  {{ template "nats-streaming-server.name" . }}
    release: {{ .Release.Name }}
  clusterIP: None
  ports:
  - name: nats
    protocol: TCP
    port: 4222
  - name: monitoring
    protocol: TCP
    port: 8222
  - name: cluster
    port: 6222
